import { styled } from "@mui/material/styles";

import {
  AppBar,
  Toolbar,
  Typography,
  Button,
  Card,
  Grid,
  SwipeableDrawer,
} from "@mui/material";

const style = {
  Root: styled("div")(({ theme }) => ({
    backgroundColor: theme.backgroundColor.secondary,
  })),
  TextTitleContainer: styled("div")(({ theme }) => ({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  })),
  TextTitle: styled(Typography)(({ theme }) => ({
    fontFamily: theme.fontFamily.secondary,
    fontSize: "1.5em",
    textAlign: "center",
    letterSpacing: "0.1em",
    paddingTop: "1vh",
    borderTop: `5px solid black`,
    marginBottom: "25px",
    fontWeight: 900,
  })),
  TextAbout: styled(Typography)(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    paddingTop: "5vh",
    textAlign: "center",
    fontSize: "1.2em",
    fontWeight: 300,
  })),
  HeaderContainer: styled(Grid)(({ theme }) => ({})),
  ImageContainer: styled("div")(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
  })),
  ImageContainerReverse: styled("div")(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "end",
  })),
  GridContainerCard: styled(Grid)(({ theme }) => ({
    ...theme.cards.primary,
  })),
  Image: styled("img")(({ theme }) => ({
    width: "75%",
    borderRadius: "5px",
    boxShadow: "5px 5px 5px #bebebe, -5px -5px 1px #ffffff",
  })),
  ProjectTitleContainer: styled("div")(({ theme }) => ({
    fontSize: "2em",
    fontFamily: theme.fontFamily.primary,
    fontStyle: "italic",
    fontWeight: 900,
    [theme.breakpoints.down("md")]: {
      fontSize: "1em",
    },
  })),
  ProjectTitleKeyword: styled("span")(({ theme }) => ({
    backgroundColor: "red",
    color: "white",
    padding: "5px",
    paddingLeft: "20px",
    paddingRight: "20px",
    borderRadius: "5px",
    marginRight: "25px",
    boxShadow: "10px 10px 2px #bebebe, -5px -5px 0px #ffffff",
  })),
  ProjectSpacer: styled("div")(({ theme }) => ({
    fontSize: "2em",
    display: "inline-block",
    color: "black",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 600,
    paddingBottom: "5px",
    borderBottom: "5px solid black",
    marginBottom: "40px",
  })),
  ProjectDescription: styled(Typography)(({ theme }) => ({
    fontSize: "1.1em",
    color: "black",
    fontWeight: 300,
    fontFamily: theme.fontFamily.primary,
    paddingBottom: "30px",
  })),
  MintButton: styled("div")(({ theme }) => ({
    padding: "5px",
    backgroundColor: "black",
    color: "white",
    borderRadius: "5px",
    textAlign: "center",
    paddingRight: "25px",
    paddingLeft: "25px",
    fontSize: "1em",
    boxShadow: "3px 3px 0px #bebebe, -5px -5px 0px #ffffff",
  })),
  MintPrice: styled("div")(({ theme }) => ({
    padding: "5px",
    borderRadius: "50px",
    textAlign: "center",
    fontFamily: theme.fontFamily.secondary,
    color: "black",
    fontSize: "0.9em",
    backgroundColor: "#F1F1F1",
    paddingRight: "20px",
    paddingLeft: "20px",
    boxShadow: "3px 3px 5px #bebebe, -5px -5px 0px #ffffff",
  })),
  ExternalLink: styled("div")(({ theme }) => ({
    padding: "5px",
    borderRadius: "5px",
    textAlign: "center",
    fontFamily: theme.fontFamily.secondary,
    fontWeight: 500,
    fontSize: "1em",
    backgroundColor: "beige",
    letterSpacing: "-1px",
    paddingRight: "10px",
    paddingLeft: "10px",
    boxShadow: "3px 3px 0px #bebebe, -5px -5px 0px #ffffff",
  })),
};

export default style;
