import { styled } from "@mui/material/styles";

import { AppBar, Toolbar, Typography, Button, Card, Grid, SwipeableDrawer } from "@mui/material";

const style = {
  Root: styled("div")(({ theme }) => ({
    height: "100%",
    width: "100%",
  })),
  TextTitleContainer: styled("div")(({ theme }) => ({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  })),
  TextTitle: styled(Typography)(({ theme }) => ({
    fontFamily: theme.fontFamily.secondary,
    fontSize: "1.5em",
    textAlign: "center",
    letterSpacing: "0.1em",
    paddingTop: "1vh",
    borderTop: `5px solid black`,
    marginBottom: "25px",
    fontWeight: 900,
  })),
  Overlay: styled("div")(({ theme }) => ({
    position: "absolute",
    bottom: 0,
    left: 0,
    paddingTop: "50px",
    background: "rgba(0, 0, 0, 0.5)",
    width: "100%",
  })),
  HeaderContainer: styled(Grid)(({ theme }) => ({})),
  ImageContainerReverse: styled("div")(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "end",
  })),
  GridContainerCard: styled(Grid)(({ theme }) => ({
    ...theme.cards.primary,
    backgroundColor: "rgba(255, 255, 255, 0.75)",
  })),
  GridContainerCard1: styled(Grid)(({ theme }) => ({
    padding: "10px",
    borderRadius: "5px",
    backgroundColor: "white",
  })),
  Image: styled("img")(({ theme }) => ({
    width: "75%",
    borderRadius: "5px",
    boxShadow: "5px 5px 5px #bebebe, -5px -5px 1px #ffffff",
  })),
  ProjectTitleContainer: styled("div")(({ theme }) => ({
    fontSize: "1.25em",
    fontFamily: theme.fontFamily.primary,
    fontStyle: "italic",
    fontWeight: 900,
  })),
  ProjectTitleContainer1: styled("div")(({ theme }) => ({
    fontSize: "1.25em",
    fontFamily: theme.fontFamily.primary,
    fontStyle: "italic",
    fontWeight: 900,
    color: "white",
  })),
  ProjectTitleKeyword: styled("span")(({ theme }) => ({
    backgroundColor: theme.backgroundColor.primary,
    color: "black",
    padding: "5px",
    paddingLeft: "20px",
    paddingRight: "20px",
    borderRadius: "2.5px",
    marginRight: "15px",
    boxShadow: "2.5px 2.5px 0px #2AFE00",
    letterSpacing: "-0.5px",
  })),
  InnerRoot1: styled("div")(({ theme }) => ({
    display: "inline-block",
    padding: "10px",
    borderRadius: "5px",
    marginTop: "25px",
    marginBottom: "-15px",
  })),
  SmallTitle: styled(Typography)(({ theme }) => ({
    fontFamily: theme.fontFamily.secondary,
    fontWeight: 900,
    marginBottom: "2.5px",
    fontSize: "0.75em",
  })),
  ProjectSpacer: styled("div")(({ theme }) => ({
    fontSize: "1em",
    marginTop: "10px",
    display: "inline-block",
    color: "black",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 600,
    paddingBottom: "5px",
    borderBottom: "5px solid black",
    marginBottom: "25px",
  })),
  ProjectDescription: styled(Typography)(({ theme }) => ({
    fontSize: "0.8em",
    color: "black",
    fontWeight: 300,
    fontFamily: theme.fontFamily.primary,
    paddingBottom: "30px",
  })),
  MintButton: styled("div")(({ theme }) => ({
    padding: "5px",
    backgroundColor: "black",
    color: "white",
    borderRadius: "2.5px",
    textAlign: "center",
    paddingRight: "25px",
    paddingLeft: "25px",
    fontFamily: theme.fontFamily.primary,
    fontSize: "0.8em",
    letterSpacing: "1px",
    fontWeight: 900,
    boxShadow: "2.5px 2.5px 0px #2AFE00",
  })),
  MintPrice: styled("div")(({ theme }) => ({
    padding: "5px",
    borderRadius: "5px",
    textAlign: "center",
    fontFamily: theme.fontFamily.secondary,
    color: "black",
    fontSize: "0.9em",
    backgroundColor: theme.backgroundColor.primary,
    paddingRight: "20px",
    paddingLeft: "20px",
    boxShadow: "1px 1px 2.5px #bebebe",
  })),
  ExternalLink: styled("div")(({ theme }) => ({
    padding: "5px",
    borderRadius: "5px",
    textAlign: "center",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 500,
    fontSize: "0.85em",
    backgroundColor: theme.backgroundColor.primary,
    paddingRight: "10px",
    paddingLeft: "10px",
    boxShadow: "1px 1px 2.5px #bebebe",
  })),
};

export default style;
