import { styled } from "@mui/material/styles";

import { AppBar, Toolbar, Typography, Button, Card, Grid, SwipeableDrawer } from "@mui/material";
import { Link } from "react-router-dom";

const triangleHeight = "5vh";

const color = "#EDEDC0";

const style = {
  Root: styled("div")(({ theme }) => ({})),
  //
  LandingScreenComponent: styled("div")(({ theme }) => ({
    height: "100vh",
  })),
  Background: styled("div")(({ theme }) => ({
    height: "100%",
    // "&:before": {
    //   content: `""`,
    //   position: "absolute",
    //   top: 0,
    //   left: 0,
    //   width: "100%",
    //   height: "100%",
    // },
    backgroundColor: theme.backgroundColor.secondary,
  })),
  HomepageBottomLink: styled("div")(({ theme }) => ({
    position: "absolute",
    bottom: "2.5%",
    left: "50%",
    transform: "translate(-50%, -50%)",
  })),
  GalleryWrap: styled("div")(({ theme }) => ({
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: "100%",
    gap: "15px",
  })),
  TitleHeader: styled("div")(({ theme }) => ({
    fontSize: "0.5em",
    letterSpacing: "1.5px",
    fontFamily: theme.fontFamily.secondary,
    padding: "20px",
  })),
  GalleryItem: styled("div")<{ img: string; $onHover: boolean }>(({ theme, img, $onHover }) => ({
    flex: $onHover ? 7 : 1,
    height: "100%",
    borderRadius: "2.5px",
    backgroundPosition: "center",
    backgroundSize: "cover",
    backgroundRepeat: "none",
    transition: "flex 0.8s ease",
    backgroundImage: `url(${img})`,
  })),
  Subtitle: styled("p")(({ theme }) => ({
    fontSize: "0.65em",
    letterSpacing: "1.5px",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    marginTop: "5px",
  })),
  GridTitle: styled(Grid)(({ theme }) => ({
    height: "calc(100vh - 100px - 100px - 7.5vh)",
  })),
  ButtonCallToAction: styled(Grid)(({ theme }) => ({
    fontSize: "15px",
    backgroundColor: "black",
    padding: "10px",
    lineHeight: "12px",
    color: "white",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    display: "inline-block",
  })),
  TitleContainer2: styled("div")(({ theme }) => ({
    position: "absolute",
    top: "100px",
    left: 0,
    right: 0,
    backgroundColor: theme.backgroundColor.secondary,
    ...theme.myBreakpoints(theme).level1,
  })),
  Title: styled("p")(({ theme }) => ({
    fontSize: "3em",
    letterSpacing: "1.5px",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    fontStyle: "italic",
    display: "inline-block",
    paddingBottom: "10px",
    marginBottom: "5px",
    borderBottom: "10px solid black",
    textShadow: `5px 5px ${theme.backgroundColor.tertiary}`,
  })),
  TitleKeywordPrefix: styled("p")(({ theme }) => ({
    fontSize: "4.5em",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 600,
    padding: "1.5px 5px 1.5px 5px",
    marginRight: "15px",
    backgroundColor: theme.backgroundColor.tertiary,
    color: "white",
    borderRadius: "2.5px",
  })),
  TitleKeyword: styled("div")(({ theme }) => ({
    fontSize: "6em",
    display: "inline-block",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 700,
    padding: "5px 15px 5px 15px",
    borderRadius: "2.5px",
    backgroundColor: "black",
    color: "white",
    boxShadow: `5px 5px 0px ${theme.backgroundColor.tertiary}`,
  })),
  TitleButton: styled("p")(({ theme }) => ({
    fontSize: "8px",
    fontFamily: theme.fontFamily.secondary,
    fontWeight: 500,
    letterSpacing: "1.25px",
    lineHeight: "13px",
  })),
  ImgIcon: styled("img")(({ theme }) => ({
    width: "25px",
    height: "25px",
  })),
  TitleVertical: styled("span")(({ theme }) => ({
    fontSize: "0.9em",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 600,
    backgroundColor: "black",
    color: "white",
    letterSpacing: "1.5px",
    writingMode: "vertical-rl",
    textOrientation: "mixed",
    padding: "7.5px 1.5px 7.5px 1.5px",
  })),
  TitleVertical1: styled("span")(({ theme }) => ({
    fontSize: "0.9em",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    writingMode: "vertical-rl",
    textOrientation: "mixed",
    fontStyle: "italic",
    padding: "7.5px 1.5px 7.5px 1.5px",
  })),
  ProjectQuickPresentation: styled("div")(({ theme }) => ({
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  })),
  ProjectPresentationTitle: styled(Typography)(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    padding: "2.5px",
    paddingLeft: "25px",
    paddingRight: "25px",
    fontSize: "0.8em",
    letterSpacing: "0.05em",
    marginTop: "15px",
    color: "black",
    backgroundColor: "white",
    textAlign: "center",
    fontWeight: 900,
    border: `2px solid ${theme.backgroundColor.tertiary}`,
    boxShadow: `5px 5px 0px ${theme.backgroundColor.tertiary}`,
    display: "flex",
    justifyItems: "center",
    alignItems: "center",
  })),
  TextStyle: styled(Typography)(({ theme }) => ({
    fontFamily: theme.fontFamily.secondary,
    fontSize: "0.3em",
    letterSpacing: "-0.05em",
    padding: "5px",
  })),
  Triangle: styled("div")(({ theme }) => ({
    position: "absolute",
    bottom: 0,
    height: 0,
    width: 0,
    borderTop: "100px solid transparent",
    borderRight: `50vw solid  ${theme.backgroundColor.primary}`,
    borderLeft: `50vw solid ${theme.backgroundColor.primary}`,
    display: "table",
    margin: "0 auto",
    paddingBottom: `${triangleHeight}`,
  })),
  LandingPageContentContainer: styled("div")(({ theme }) => ({
    height: "100vh",
    width: "100%",
  })),
  LandingPageContent: styled("div")(({ theme }) => ({
    height: "100%",
    width: "100%",
  })),
  GoToAppButton: styled(Link)(({ theme }) => ({
    textDecoration: "none",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    letterSpacing: "-0.1px",
    fontSize: "0.9em",
    transform: "skew(-20deg)",
    transition: "0.25s",
    padding: "5px",
    backgroundColor: "black",
    color: "white",
    "&:hover": {
      color: "black",
      backgroundColor: theme.backgroundColor.primary,
    },
  })),

  //
  DripComponent: styled("div")(({ theme }) => ({
    background: `linear-gradient(0deg, ${theme.backgroundColor.secondary} 0%, ${theme.backgroundColor.primary} 50%)`,
  })),
  DripComponentP1: styled(Grid)(({ theme }) => ({
    ...theme.myBreakpoints(theme).level1,
  })),
  DripComponentP2: styled(Grid)(({ theme }) => ({
    ...theme.myBreakpoints(theme).level0,
  })),
  DripComponentP3: styled(Grid)(({ theme }) => ({
    ...theme.myBreakpoints(theme).level2,
  })),
  DripComponentP4: styled(Grid)(({ theme }) => ({
    ...theme.myBreakpoints(theme).level4,
  })),
  DripWarningContainer: styled("div")(({ theme }) => ({
    marginTop: "35px",
    padding: "15px",
    backgroundColor: theme.backgroundColor.secondary,
    borderRadius: "5px",
  })),
  ViewTitle: styled("div")<{ big?: boolean; shadow?: boolean; color?: string }>(
    ({ theme, shadow = true, color = "#EDEDC0" }) => ({
      fontSize: "2em",
      letterSpacing: "1px",
      fontFamily: theme.fontFamily.tertiary,
      fontWeight: 300,
      marginBottom: "10px",
      display: "inline-block",
      borderRadius: "2.5px",
      background: `linear-gradient(${color}, ${color}) 0 95% / 100% 32.5% no-repeat`,
    })
  ),
  ViewTitle1: styled("div")(({ theme }) => ({
    fontSize: "100px",
    letterSpacing: "1px",
    fontFamily: theme.fontFamily.tertiary,
    fontWeight: 500,
    display: "inline-block",
    margin: "0 auto",
    textAlign: "center",
    fontStyle: "italic",
    marginBottom: "100px",
    background: `linear-gradient(${color}, ${color}) 0 95% / 100% 32.5% no-repeat`,
  })),
  ViewTitle2: styled("div")<{ color?: string }>(({ theme, color = "#EDEDC0" }) => ({
    fontSize: "1.1em",
    letterSpacing: "1px",
    fontFamily: theme.fontFamily.tertiary,
    fontWeight: 600,
    marginBottom: "25px",
    display: "inline-block",
    fontStyle: "italic",
  })),
  Button2: styled("div")(({ theme }) => ({
    fontSize: "1.25em",
    letterSpacing: "0.5px",
    fontFamily: theme.fontFamily.tertiary,
    padding: "2.5px 15px 2.5px 15px",
    borderRadius: "5px",
    color: "white",
    fontStyle: "ita lic",
    fontWeight: 500,
    backgroundColor: "black",
    display: "inline-block",
  })),
  Sbu: styled("span")<{ color?: string; bold?: any }>(
    ({ theme, color = "#EDEDC0", bold = "bold" }) => ({
      background: `linear-gradient(${color}, ${color}) 0 95% / 100% 32.5% no-repeat`,
      fontWeight: bold,
    })
  ),
  Premier: styled("span")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    letterSpacing: "-0.1px",
    fontSize: "0.95em",
    display: "inline-block",
    transform: "skew(-20deg)",
  })),
  View2Content: styled("div")(({ theme }) => ({
    fontSize: "1.15em",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 500,
    lineHeight: "2em",
  })),
  MoreLinkContainer: styled("div")(({ theme }) => ({
    marginTop: "35px",
    display: "inline-block",
  })),
  MoreLink: styled("div")(({ theme }) => ({
    fontSize: "0.8em",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    letterSpacing: "1.5px",
    borderBottom: "2.5px solid black",
    paddingBottom: "5px",
  })),

  //
  View3: styled("div")(({ theme }) => ({
    ...theme.myBreakpoints(theme).level1,
  })),
  View3StepName: styled(Typography)(({ theme }) => ({
    fontSize: "1rem",
    paddingLeft: "15px",
    paddingRight: "15px",
    borderRadius: "5px",
    fontStyle: "italic",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    backgroundColor: theme.backgroundColor.secondary,
    color: "black",
    textAlign: "center",
    display: "table",
    margin: "0 auto",
  })),
  View3Char: styled("div")(({ theme }) => ({
    fontSize: "3em",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    textAlign: "center",
  })),
  View3Container: styled("div")(({ theme }) => ({
    paddingTop: "25px",
    paddingBottom: "25px",
  })),

  //
  SocietyComponent: styled("div")(({ theme }) => ({
    ...theme.myBreakpoints(theme).level1,
    backgroundColor: theme.backgroundColor.secondary,
    paddingTop: "7.5vh",
    paddingBottom: "7.5vh",
  })),
  Titlea: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    color: "black",
    fontSize: "1.75em",
    fontWeight: 900,
    marginBottom: "35px",
    letterSpacing: "-0.5px",
    display: "inline-block",
  })),
  Button: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    backgroundColor: theme.backgroundColor.secondary,
    color: "black",
    borderRadius: "25px",
    padding: "5px 15px 5px 15px",
    fontSize: "0.75em",
    fontWeight: 700,
    letterSpacing: "1.5px",
  })),
  //
  RoadmapComponent: styled("div")(({ theme }) => ({
    ...theme.myBreakpoints(theme).level1,
    backgroundColor: theme.backgroundColor.primary,
    paddingTop: "7.5vh",
    paddingBottom: "7.5vh",
  })),
  //
  TeamComponent: styled("div")(({ theme }) => ({
    ...theme.myBreakpoints(theme).level1,
    backgroundColor: theme.backgroundColor.secondary,
    paddingTop: "7.5vh",
    paddingBottom: "7.5vh",
  })),
  TeamContainer: styled("div")(({ theme }) => ({
    backgroundColor: theme.backgroundColor.primary,
    padding: "25px",
    borderRadius: "5px",
  })),
  ImgTeam: styled("img")(({ theme }) => ({
    width: "100%",
    borderRadius: "5px",
  })),
  TeamName: styled(Typography)(({ theme }) => ({
    ...theme.titles(theme).primary,
    paddingLeft: "5px",
  })),
  TeamNameTitle: styled(Typography)(({ theme }) => ({
    ...theme.titles(theme).secondary,
    opacity: "35%",
    paddingLeft: "5px",
    marginBottom: "5px",
  })),
  CenteredGridItem: styled(Grid)<{ justifyContent?: string }>(
    ({ theme, justifyContent = "center" }) => ({
      display: "flex",
      alignItems: "center",
      justifyContent: justifyContent,
    })
  ),
  TitleCollection: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontSize: "15px",
    padding: "10px",
    fontWeight: 900,
    letterSpacing: "-0.5px",
  })),
  TitleDrip: styled("div")(({ theme }) => ({
    fontFamily: "anton",
    fontSize: "4em",
    fontWeight: 900,
    letterSpacing: "-0.5px",
  })),
  TextLinkHeader: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontSize: "13.5px",
    fontWeight: 500,
    letterSpacing: "-0.5px",
  })),
  TextHeader: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontSize: "5rem",
    fontWeight: 600,
    letterSpacing: "-0.5px",
    padding: "10px",
    textAlign: "right",
    lineHeight: "1.1em",
    // textShadow: `5px 5px ${theme.backgroundColor.tertiary}`,
  })),
  LabsComponent: styled("div")(({ theme }) => ({
    paddingTop: ".75vh",
    paddingBottom: ".75vh",
    height: "100%",
    width: "100%",
  })),
  Sentence: styled("div")<{ fontSize?: string }>(({ theme, fontSize = "17.5px" }) => ({
    fontFamily: theme.fontFamily.primary,
    fontSize: fontSize,
    color: "black",
    fontWeight: 900,
    paddingRight: "35px",
    textAlign: "center",
    transform: "skew(-20deg)",
    whiteSpace: "nowrap",
  })),

  //
  ContractsComponent: styled("div")(({ theme }) => ({
    ...theme.myBreakpoints(theme).level1,
    backgroundColor: theme.backgroundColor.secondary,
    paddingTop: "7.5vh",
    paddingBottom: "7.5vh",
  })),
  ContractsTitle: styled(Typography)(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontSize: "1em",
    fontWeight: 900,
    marginBottom: "20px",
    display: "inline-block",
    borderBottom: "2.5px solid black",
  })),
  ContractsName: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontWeight: 700,
    marginRight: "15px",
    fontSize: "0.85em",
  })),
  ContractsAddy: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontSize: "0.8em",
    opacity: "50%",
    textDecoration: "underline",
  })),

  RoadMapItemStep: styled(Typography)(({ theme }) => ({
    color: "black",
    borderRadius: "5px",
    display: "inline-block",
    paddingLeft: "10px",
    paddingRight: "10px",
    fontFamily: "montserrat",
    fontWeight: 700,
    fontSize: "0.8em",
  })),
  RoadMapItem: styled("div")(({ theme }) => ({
    padding: "10px",
    borderRadius: "5px",
    boxShadow: `10px 10px 2.5px ${theme.backgroundColor.secondary}`,
    backgroundColor: `white`,
    marginLeft: "10px",
    marginBottom: "35px",
  })),
  RoadMapItemTitle: styled(Typography)(({ theme }) => ({
    paddingLeft: "10px",
    paddingRight: "10px",
    fontStyle: "italic",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    fontSize: "1.1em",
    color: "black",
    marginBottom: "15px",
  })),
  RoadMapItemType: styled(Typography)(({ theme }) => ({
    fontSize: "0.75em",
    padding: "2.5px",
    paddingLeft: "10px",
    paddingRight: "10px",
    fontWeight: 900,
    letterSpacing: "0.5px",
    fontFamily: theme.fontFamily.primary,
    backgroundColor: theme.backgroundColor.secondary,
    borderRadius: "5px",
  })),
  RoadMapItemContent: styled(Typography)(({ theme }) => ({
    paddingLeft: "10px",
    paddingRight: "10px",
    fontFamily: "montserrat",
    fontWeight: 300,
    fontSize: "1em",
    color: "black",
    opacity: "75%",
  })),
  RoadMapItem2: styled("div")(({ theme }) => ({
    padding: "10px",
    borderRadius: "5px",
    boxShadow: `-10px 10px 2.5px ${theme.backgroundColor.secondary}`,
    backgroundColor: `white`,
    textAlign: "start",
    marginRight: "10px",
    marginBottom: "35px",
  })),
  FooterSplitContainer: styled("div")(({ theme }) => ({
    ...theme.myBreakpoints(theme).level1,
    backgroundColor: theme.backgroundColor.secondary,
  })),
  FooterSplit: styled("div")(({ theme }) => ({
    height: "2px",
    opacity: "50%",
    backgroundColor: theme.backgroundColor.tertiary,
  })),
};

export default style;
