/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CryptopunksInterface__factory } from "./CryptopunksInterface__factory";
export { ICryptopunks__factory } from "./ICryptopunks__factory";
