/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { FC, forwardRef, Ref, useEffect, useRef } from "react";
import { GLTF } from "three-stdlib";
import { Center, useGLTF } from "@react-three/drei";
import useTexture, { loadTextureToObject } from "../utils/loaderTexture";
import React from "react";
import { useImperativeHandle } from "react";
import { useFrame, useLoader } from "@react-three/fiber";

import { TextureLoader } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Tube: THREE.Mesh;
    Tube2_4: THREE.Mesh;
    Tube2_5: THREE.Mesh;
    Tube_1: THREE.Mesh;
    Tube2_1_1: THREE.Mesh;
    Tube2_1_2: THREE.Mesh;
    Tube_2: THREE.Mesh;
    Tube2_2_1: THREE.Mesh;
    Tube2_2_2: THREE.Mesh;
    Tube_3: THREE.Mesh;
    Tube2_3_1: THREE.Mesh;
    Tube2_3_2: THREE.Mesh;
    Absorber1: THREE.Mesh;
    Trucks: THREE.Mesh;
    Deck: THREE.Mesh;
    Placeholder: THREE.Mesh;
  };
  materials: {
    Wheels: THREE.MeshStandardMaterial;
    Trucks: THREE.MeshStandardMaterial;
    Deck: THREE.MeshStandardMaterial;
    Placeholder: THREE.MeshStandardMaterial;
  };
};

const modelPath = "/models/skate/skate-transformed.glb";

export type props = {
  _id: number;
  //
  deckRef: React.RefObject<JSX.IntrinsicElements["mesh"]>;
  placeholderRef: React.RefObject<JSX.IntrinsicElements["mesh"]>;
};

const defaultDeckTexture = "/models/skate/textures/default-deck.png";
const defaultPlaceholderTexture = "/models/skate/textures/default-placeholder.png";

const Skate = forwardRef<{}, props & JSX.IntrinsicElements["group"]>(({ ...props }, ref) => {
  useImperativeHandle(ref, () => ({
    getAlert() {
      loadTextureToObject(defaultDeckTexture, deckRef);
      loadTextureToObject(defaultPlaceholderTexture, placeholderRef);
    },
  }));

  const group = useRef<THREE.Group>(null);

  // setup refs
  const deckRef = props.deckRef;
  const placeholderRef = props.placeholderRef;

  // model
  const { nodes, materials } = useGLTF(modelPath) as GLTFResult;

  // Deck
  materials.Deck.color = null as any;
  materials.Deck.toneMapped = false;

  // // Placeholder
  materials.Placeholder.color = null as any;
  materials.Placeholder.toneMapped = false;

  console.log(props._id);

  // itemId
  const itemId = "#" + "23";

  const canvas = document.createElement("canvas");

  const ctx = canvas.getContext("2d") as any;
  ctx.canvas.width = 500;
  ctx.canvas.height = 500;
  ctx.fillStyle = "rgba(0, 0, 0, 0)";
  ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);

  ctx.textAlign = "center";
  ctx.font = "700 50px montserrat";
  ctx.fillStyle = "black";
  ctx.fillText(itemId, ctx.canvas.width / 2, ctx.canvas.height / 2);

  const newMaterial = new THREE.CanvasTexture(canvas);

  useEffect(() => {
    loadTextureToObject(defaultDeckTexture, deckRef);
    loadTextureToObject(defaultPlaceholderTexture, placeholderRef);
  }, []);

  return (
    <group ref={group} {...props}>
      <Center alignTop>
        <group rotation={[Math.PI, -Math.PI / 2, Math.PI / 2]} dispose={null}>
          <mesh
            ref={deckRef}
            geometry={nodes.Deck.geometry}
            material={materials.Deck}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            ref={placeholderRef}
            geometry={nodes.Placeholder.geometry}
            material={materials.Placeholder}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh position={[12.8, 6.75, 0]} rotation={[Math.PI / 2, 0, -Math.PI / -2]}>
            <planeGeometry args={[10, 10, 10, 10]} />
            <meshBasicMaterial transparent map={newMaterial} />
          </mesh>
        </group>
      </Center>
    </group>
  );
});

useGLTF.preload(modelPath);

export default Skate;
