/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cryptopunksInterfaceSol from "./CryptopunksInterface.sol";
export type { cryptopunksInterfaceSol };
import type * as sources from "./sources";
export type { sources };
export type { ITokenInterface } from "./ITokenInterface";
