/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenInterface,
  ITokenInterfaceInterface,
} from "../../../contracts/tokens/ITokenInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITokenInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenInterfaceInterface {
    return new utils.Interface(_abi) as ITokenInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenInterface {
    return new Contract(address, _abi, signerOrProvider) as ITokenInterface;
  }
}
