/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICryptopunks, ICryptopunksInterface } from "../ICryptopunks";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "punkIndexToAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICryptopunks__factory {
  static readonly abi = _abi;
  static createInterface(): ICryptopunksInterface {
    return new utils.Interface(_abi) as ICryptopunksInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICryptopunks {
    return new Contract(address, _abi, signerOrProvider) as ICryptopunks;
  }
}
