/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMutator, IMutatorInterface } from "../IMutator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMutator__factory {
  static readonly abi = _abi;
  static createInterface(): IMutatorInterface {
    return new utils.Interface(_abi) as IMutatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMutator {
    return new Contract(address, _abi, signerOrProvider) as IMutator;
  }
}
