/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CryptopunksMutator } from "./CryptopunksMutator";
export type { ICryptopunks } from "./ICryptopunks";
