/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/af1/AIR.gltf");
  const new_mtl = new THREE.MeshPhongMaterial({ color: "#66533C" });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Object056_1.geometry} material={new_mtl} />
      <mesh
        geometry={nodes.Object062_1.geometry}
        material={nodes.Object062_1.material}
      />
      <mesh
        geometry={nodes.Object040_1.geometry}
        material={nodes.Object040_1.material}
      />
      <mesh
        geometry={nodes.Object043_1.geometry}
        material={nodes.Object043_1.material}
      />
      <mesh
        geometry={nodes.Object044_1.geometry}
        material={nodes.Object044_1.material}
      />
      <mesh
        geometry={nodes.Shape003_1.geometry}
        material={nodes.Shape003_1.material}
      />
      <mesh
        geometry={nodes.Object051_1.geometry}
        material={nodes.Object051_1.material}
      />
      <mesh
        geometry={nodes.Object053_1.geometry}
        material={nodes.Object053_1.material}
      />
      <mesh
        geometry={nodes.Shape004_1.geometry}
        material={nodes.Shape004_1.material}
      />
      <mesh
        geometry={nodes.Object055_1.geometry}
        material={nodes.Object055_1.material}
      />
      <mesh
        geometry={nodes.Object042_1.geometry}
        material={nodes.Object042_1.material}
      />
      <mesh
        geometry={nodes.Object054_1.geometry}
        material={nodes.Object054_1.material}
      />
      <mesh
        geometry={nodes.Object026_1.geometry}
        material={nodes.Object026_1.material}
      />
      <mesh
        geometry={nodes.Box002_1.geometry}
        material={nodes.Box002_1.material}
      />
      <mesh
        geometry={nodes.Plane014_1.geometry}
        material={nodes.Plane014_1.material}
      />
      <mesh
        geometry={nodes.Text002_1.geometry}
        material={nodes.Text002_1.material}
      />
      <mesh
        geometry={nodes.Text001_1.geometry}
        material={nodes.Text001_1.material}
      />
      <mesh
        geometry={nodes.Object034_1.geometry}
        material={nodes.Object034_1.material}
      />
      <mesh
        geometry={nodes.Object036_1.geometry}
        material={nodes.Object036_1.material}
      />
      <mesh
        geometry={nodes.Object041_1.geometry}
        material={nodes.Object041_1.material}
      />
      <mesh
        geometry={nodes.Line003_1.geometry}
        material={nodes.Line003_1.material}
      />
      <mesh
        geometry={nodes.Line004_1.geometry}
        material={nodes.Line004_1.material}
      />
      <mesh
        geometry={nodes.Object014_1.geometry}
        material={nodes.Object014_1.material}
      />
      <mesh
        geometry={nodes.Object059_1.geometry}
        material={nodes.Object059_1.material}
      />
      <mesh
        geometry={nodes.Object060_1.geometry}
        material={nodes.Object060_1.material}
      />
      <mesh
        geometry={nodes.Box003_1.geometry}
        material={nodes.Box003_1.material}
      />
      <mesh
        geometry={nodes.Object068_1.geometry}
        material={nodes.Object068_1.material}
      />
      <mesh
        geometry={nodes["02_1"].geometry}
        material={nodes["02_1"].material}
      />
      <mesh
        geometry={nodes.Object064_1.geometry}
        material={nodes.Object064_1.material}
      />
      <mesh geometry={nodes["01_1"].geometry} material={new_mtl} />
      <mesh geometry={nodes.Plane015_1.geometry} material={new_mtl} />
      <mesh
        geometry={nodes.Object065_1.geometry}
        material={nodes.Object065_1.material}
      />
      <mesh
        geometry={nodes.Object066_1.geometry}
        material={nodes.Object066_1.material}
      />
      <mesh geometry={nodes.Object067_1.geometry} material={new_mtl} />
      <mesh
        geometry={nodes.Object069_1.geometry}
        material={nodes.Object069_1.material}
      />
      <mesh
        geometry={nodes.Object061_1.geometry}
        material={nodes.Object061_1.material}
      />
      <mesh
        geometry={nodes.Line009_1.geometry}
        material={nodes.Line009_1.material}
      />
    </group>
  );
}

useGLTF.preload("/AIR.gltf");
