/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CryptopunksInterface } from "./CryptopunksInterface";
export type { ICryptopunks } from "./ICryptopunks";
