/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITestERC721__factory } from "./ITestERC721__factory";
export { TestERC721__factory } from "./TestERC721__factory";
