import { styled } from "@mui/material/styles";

import { Grid, Typography } from "@mui/material";
import { url } from "inspector";
import ImgWave from "@/common/assets/images/wave.png";

const footerHeight = "25px";
const itemTitleContainerWidth = "75px";

const style = {
  Root: styled("div")(({ theme }) => ({
    ...theme.myBreakpoints.static,
  })),
  HomeScreenContainer: styled("div")(({ theme }) => ({
    paddingTop: theme.header.height,
    paddingBottom: "25px",
    minHeight: "100vh",
    boxSizing: "border-box",
  })),
  HomeScreen: styled("div")(({ theme }) => ({
    backgroundColor: theme.colors.primary,
    padding: "25px",
    borderRadius: "5px",
    minHeight: `calc(100vh - ${theme.header.height} - 25px)`,
    boxSizing: "border-box",
  })),
  RootInner: styled("div")(({ theme }) => ({
    paddingTop: theme.header.height,
    paddingBottom: "25px",
    height: `100%`,
    width: `100%`,
    boxSizing: "border-box",
  })),
  GalleryWrapContainer: styled("div")(({ theme }) => ({
    width: "100%",
  })),
  GalleryWrap: styled("div")(({ theme }) => ({
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: "100%",
    gap: "1.5px",
  })),
  GalleryItem: styled("div")<{ color: string; $onHover: boolean; disabled: boolean }>(
    ({ theme, color, $onHover, disabled }) => ({
      "&:before": {
        content: `""`,
        display: "block",
        position: "absolute",
        backgroundImage: $onHover ? `url(${color})` : "",
        backgroundColor: "transparent",
        filter: "grayscale(75%)",
        top: 0,
        left: 0,
        objectPosition: "10% 10%",
        backgroundPosition: "10% 10%",
        backgroundSize: "cover",
        objectFit: "contain",
        width: "100%",
        height: "100%",
        imageRendering: "pixelated",
        WebkitPrintColorAdjust: "exact",
        borderRadius: "5px",
      },
      position: "relative",
      flex: $onHover ? 10 : 1,
      width: "100%",
      backgroundColor: $onHover ? "" : "black",
      transition: "flex 0.8s ease",
      color: $onHover ? "white" : "white",
      cursor: !disabled ? ($onHover ? "auto" : "pointer") : "auto",
      borderRadius: "5px",
    })
  ),
  ContainerExempleDrip: styled("div")(({ theme }) => ({
    backgroundColor: "white",
    padding: "15px",
    borderRadius: "5px",
    boxShadow: `2.5px 2.5px 2.5px ${theme.colors.secondary}, -.1px -.1px 1.5px ${theme.colors.secondary}`,
  })),
  ContainerExempleDripContainer: styled("div")(({ theme }) => ({
    backgroundColor: "white",
    paddingLeft: "5px",
    paddingRight: "5px",
    borderRadius: "5px",
  })),
  SubTitle6: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.tertiary,
    fontWeight: 800,
    // color: "white",
    backgroundColor: theme.colors.secondary,
    fontSize: "0.95em",
    // display: "inline-block",
    float: "right",
    // textAlign: "right",
    padding: "5px",
    borderRadius: "5px",
  })),
  SubTitle4: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.tertiary,
    fontWeight: 800,
    fontSize: "1em",
  })),
  ContainerContract: styled("div")(({ theme }) => ({
    // backgroundColor: theme.backgroundColor.primary,
    // padding: "10px",
    borderRadius: "5px",
    fontFamily: theme.fontFamily.primary,
    fontWeight: 800,
    fontSize: "0.7em",
  })),
  ContainerInfoDiv: styled("div")(({ theme }) => ({
    padding: "10px",
    backgroundColor: theme.colors.primary,
    borderRadius: "5px",
  })),
  InfoDivItemName: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    fontSize: "0.8em",
    letterSpacing: "1.25px",
    marginBottom: "7.5px",
  })),
  GalleryItemContainer: styled("div")(({ theme }) => ({
    position: "absolute",
    top: 0,
    left: 0,
    width: itemTitleContainerWidth,
    paddingTop: "15px",
    paddingBottom: "15px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    borderRadius: "5px",
    backgroundColor: "transparent",
    // padding: "15px",
    boxSizing: "border-box",
  })),
  GalleryItemTitle: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    fontSize: "2em",
    writingMode: "vertical-rl",
    transform: "scale(-1)",
    letterSpacing: "0.5px",
  })),
  LiveTitle: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    fontSize: "0.9em",
    writingMode: "vertical-rl",
    transform: "scale(-1)",
  })),
  ButtonDiscover: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    fontSize: "1em",
    backgroundColor: "white",
    color: "black",
    padding: "10px",
    transition: "all .2s ease-in-out",
    borderBottomRightRadius: "5px",
    borderBottomLeftRadius: "5px",
    ":hover": {
      cursor: "pointer",
      backgroundColor: "black",
      color: "white",
    },
  })),
  ItemName: styled("div")(({ theme }) => ({
    fontFamily: theme.fontFamily.primary,
    fontWeight: 900,
    fontSize: "2.25em",
    backgroundColor: "red",
    color: "white",
    padding: "10px",
    borderTopRightRadius: "5px",
    borderTopLeftRadius: "5px",
  })),
  ContainerExplore: styled("div")<{ isVisible: boolean }>(({ theme, isVisible }) => ({
    position: "absolute",
    left: `calc(50% + calc(${itemTitleContainerWidth} / 2))`,
    top: "50%",
    transform: "translate(-50%,-50%)",
    transition: "all 0.5s ease-in-out",
    opacity: isVisible ? "100%" : "0%",
    scale: isVisible ? "scale(0.5)" : "0%",
  })),
};

export default style;
